output_directory: articles
template_path: .news-writer/news-article-template.md
agents:
  planner:
    max_tokens: 2000
    temperature: 0.0
  writer:
    max_tokens: 4000
    temperature: 0.3
categories:
  - name: "Development"
    description: "Software development, programming languages, and engineering practices"
    subcategories:
      - "Programming"
      - "Software Engineering"
      - "Web Development"
      - "Mobile Development"
      - "DevOps"

  - name: "Artificial Intelligence"
    description: "AI, machine learning, and intelligent systems"
    subcategories:
      - "Large Language Models"
      - "Machine Learning"
      - "Computer Vision"
      - "Natural Language Processing"
      - "Deep Learning"

  - name: "Technology"
    description: "General technology trends, innovations, and digital transformation"
    subcategories:
      - "Technology"
      - "Innovation"
      - "Digital Transformation"
      - "Emerging Technologies"

  - name: "Data & Analytics"
    description: "Data science, analytics, databases, and big data processing"
    subcategories:
      - "Data Science"
      - "Analytics"
      - "Databases"
      - "Big Data"
      - "Data Engineering"

  - name: "Business & Strategy"
    description: "Entrepreneurship, business strategy, and market insights"
    subcategories:
      - "Business"
      - "Startups"
      - "Entrepreneurship"
      - "Strategy"
      - "Marketing"

  - name: "Security"
    description: "Cybersecurity, privacy, and security best practices"
    subcategories:
      - "Cybersecurity"
      - "Privacy"
      - "Security"
      - "Authentication"

  - name: "Infrastructure"
    description: "Cloud computing, DevOps, and system architecture"
    subcategories:
      - "Cloud Computing"
      - "Infrastructure"
      - "DevOps"
      - "System Architecture"

  - name: "Crypto & Blockchain"
    description: "Cryptocurrency, blockchain technology, and decentralized systems"
    subcategories:
      - "Blockchain"
      - "Cryptocurrency"
      - "Decentralized Finance"
      - "Web3"
