output_directory: articles
template_path: .news-writer/news-article-template.md
agents:
  planner:
    max_tokens: 2000
    temperature: 0.0
  writer:
    max_tokens: 4000
    temperature: 0.3
categories:
  - "Development/Programming"
  - "Development/Software Engineering"
  - "Development/Web Development"
  - "Development/Mobile Development"
  - "Development/DevOps"
  - "Artificial Intelligence/Large Language Models"
  - "Artificial Intelligence/Machine Learning"
  - "Artificial Intelligence/Computer Vision"
  - "Artificial Intelligence/Natural Language Processing"
  - "Artificial Intelligence/Deep Learning"
  - "Technology/Innovation"
  - "Technology/Digital Transformation"
  - "Technology/Emerging Technologies"
  - "Data & Analytics/Data Science"
  - "Data & Analytics/Analytics"
  - "Data & Analytics/Databases"
  - "Data & Analytics/Big Data"
  - "Data & Analytics/Data Engineering"
  - "Business & Strategy/Business"
  - "Business & Strategy/Startups"
  - "Business & Strategy/Entrepreneurship"
  - "Business & Strategy/Strategy"
  - "Business & Strategy/Marketing"
  - "Security/Cybersecurity"
  - "Security/Privacy"
  - "Security/Authentication"
  - "Infrastructure/Cloud Computing"
  - "Infrastructure/System Architecture"
  - "Crypto & Blockchain/Blockchain"
  - "Crypto & Blockchain/Cryptocurrency"
  - "Crypto & Blockchain/Decentralized Finance"
  - "Crypto & Blockchain/Web3"
